name: Safety Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install safety==2.3.0
          pip install flask==2.0.3
          pip install requests==2.26.0

      - name: Run Safety
        run: safety check --full-report --exit-code 1
