name: Safety Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          pip install --upgrade pip
          pip install safety==2.3.0
          pip install -r requirements.txt

      - name: Run Safety
        run: safety check --file=requirements.txt --full-report --exit-code 1
